version: '3.8'

services:
  nominatim:
    image: mediagis/nominatim:4.2
    container_name: nominatim
    environment:
      - PBF_URL=http://download.geofabrik.de/north-america/us-northeast-latest.osm.pbf     
      - THREADS=64 
    ports:
      - "8080:8080"
    shm_size: '16gb'
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main


volumes:
  nominatim-data:
