[tool.poetry]
name = "gpx2township"
version = "0.1.0"
description = ""
authors = ["Fab <fabian@fabianhaupt.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
geopy = "^2.3.0"
gpxpy = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
